### PR TITLE
fix for compile error under java 11

### PR DESCRIPTION
**Pull request by rbelohlavek**
See discussion here: https://dev.clojure.org/jira/browse/CRRBV-18?focusedCommentId=49545&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-49545

### CODE REVIEW

**Comment by tonsky** [comment]
Thanks! I’ll take a look later

**Comment by magnars** [comment]
This issue is stopping us from upgrading to JDK11. Please consider merging this PR. 👍

**Comment by tonsky** [comment]
Will do shortly!

**Comment by Harleqin** [comment]
Need the type hints be so ugly?  Couldn't `^Object` work?

**Comment by magnars** [comment]
They probably do not need to be so ugly. Clojure core uses `^objects`.

**Comment by tonsky** [comment]
Thx! Merged in 0.16.7

**Pull request closed without merging**
