### PR TITLE
Query function bindings fail to handle colliding bindings

### PR DESCRIPTION
**Pull request by abrooks**
Here's a fairly minimal example.

```
user> (let [conn (ds/create-conn {})]
        (ds/q '[:find ?n
                :where [(identity 1) ?n]
                       [(identity 2) ?n]]
              @conn))
#{[1]}
user>
```

The above should return the empty set `#{}`.

I've include two commits. One with a series of tests showing the failing cases followed by another which fixes the issue in the way which seems most reasonable. I'm interested to know if you concur with the fix.

When fixing this, I saw that `filter-by-pred` also uses `conj` instead of `collapse-rels`. This is likely fine since there are no bindings for predicates but I thought I'd mention it in passing.

Let me know if you'd like me to make any adjustments to this pull request!

-A.

### CODE REVIEW

**Comment by abrooks** [comment]
I've created issue #141 to track this as an issue. I probably should have filed an issue first. Let me know what the preferred procedure is for future issues/pull-requests.

Thanks!

**Comment by tonsky** [comment]
Sorry, I’ll look into it soon.

**Comment by tonsky** [comment]
Thanks, this is really a proper fix in just the right place. And test coverage — thanks for great PR!

**Comment by abrooks** [comment]
Thanks for a great project — I hope to contribute more in the future!

**Pull request closed without merging**
