### PR TITLE
Loop/recur based pull API

### PR DESCRIPTION
**Pull request by dthume**
Improve parsing of pull expressions and handling of components (:db/id) based on feedback from @tonsky. This still doesn't have the extra step between parsing and pull execution, but I believe all the other line notes have been addressed.

### CODE REVIEW

**Comment by dthume** [comment]
I've added the conversion from raw parsed records into a canonical representation as you suggested - good call! the resulting code is smaller now. I've also shaved down the pull loop as much as I was able to.

**Comment by tonsky** [comment]
That’s amazing! Thanks for such a big contribution!

**Comment by FrigoEU** [comment]
I'm eager to try this out, but I can't seem to get this to work. I'm using datascript 0.9.0, but keep getting errors that pull is not available, neither as pull-api or in queries. Do I need to pull in a special package or something? Probably doing something very stupid...

Project.clj: 
:dependencies [[org.clojure/clojure "1.7.0-alpha4"]
                 [org.clojure/clojurescript "0.0-2727" :scope "provided"]
                 [com.cognitect/transit-clj "0.8.259" :exclusions [org.msgpack/msgpack org.clojure/test.check]]
                 [com.cognitect/transit-cljs "0.8.192"]
                 [datascript "0.9.0"]
                 [leiningen "2.5.0"]]

(ns myproject.core
  (:require [datascript :as d]
            [datascript.core :as dc]
            [cognitect.transit :as transit]
            [clojure.string :as str])
  (:require-macros [myproject.macros :as m]))

(d/pull @conn '[:student/firstname :student/lastname] 1)

**Comment by dthume** [comment]
Have you tried cleaning out any build artifacts with, e.g, `lein clean`? I've run a clean build here and `d/pull` is definitely found.

**Comment by FrigoEU** [comment]
I could have sworn I did that before... Anyway it's working now and looking good. Great PR!

**Pull request merged**
