### PR TITLE
make conn? work with any atom-like entity in cljs

### PR DESCRIPTION
**Pull request by piranha**

### CODE REVIEW

**Comment by piranha** [comment]
I couldn't find a protocol for Clojure's side, so I left `instance?` in place.

**Comment by tonsky** [comment]
I think check should be `IDeref` for both Clojure and ClojureScript. We need conn to `deref` to DB, so we should check exactly for that.

**Comment by piranha** [comment]
Ok, also I'm not sure why tests failed - looking at that.

**Comment by tonsky** [comment]
Merged in 0.13.1

**Pull request closed without merging**
