### PR TITLE
Diff dbs with different types of the same attribute (closes #369)

### LINKED ISSUE #369: Here are two cases of ClassCastException
jvm 14, clojure 1.10.1, datascipt 1.0.1

# First case

```clojure
(-> (d/empty-db {:attr {:db/cardinality :db.cardinality/many}})
    (d/db-with [[:db/add -1 :attr 1]
                [:db/add -1 :attr "str"]]))
;; BOOM
```

```clojure
(-> (d/empty-db)
    (d/db-with [[:db/add -1 :attr 1]
                [:db/add -2 :attr "str"]]))
;; it's ok
```

It fails with ClassCastException in case of  `db.cardinality/many` but works in case of `db.cardinality/one`.

# Second case

```clojure
(let [db1 (-> (d/empty-db)
              (d/db-with [[:db/add -1 :attr 1]]))
      db2 (-> (d/empty-db)
              (d/db-with [[:db/add -1 :attr "str"]]))]
  (clojure.data/diff db1 db2))

;; BOOM
```

Is PR welcome? :-)

### PR DESCRIPTION
**Pull request by darkleaf**

### CODE REVIEW

**Comment by tonsky** [comment]
Looks great! I think you need ClassCastException -> Exception though?

**Comment by darkleaf** [comment]
No, we don't. We should notify about any exception but ClassCastException. In the JS, we can't recognize the error type so there is only `js/Error`.

**Comment by tonsky** [comment]
Yeah you are right, sorry.

**Comment by tonsky** [comment]
Pushed 1.0.2

**Pull request merged**
